// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
Open the links in the URL keys in the Outputs tab to navigate to the web pages that shows whether the deployment was successful. The template uses HTTPS and adopts a private certificate for better security, so you may encounter an alert window regarding the certificate being untrusted when opening the web page.

== Deletion
To delete the ISMS-P Quick Start resources after deployment, perform the following:

[[step-1.-delete-the-cloudformation-template]]
=== Step 1. Delete the CloudFormation template

1.  Navigate to CloudFormation on the AWS console. Select *the name of the ISMS-P Quick Start stack* you deployed. Take note that you must choose the name of stack you used to deploy the Quick Start, instead of the duplicate stack that had been created during the stack creation.
2.  Select the *Delete* menu on top of the screen and choose *Delete* *stack* when the delete confirmation window pops up.
3.  After the deletion is complete, the *state* will change from DELETE_IN_PROGRESS to *DELETE_COMPLETE*.

[[step-2.-identify-and-cleanse-undeleted-resources]]
=== Step 2. Identify and cleanse undeleted resources

1.  Though unlikely, some resources could be left undeleted if they were in use or due to some issues such as permission restrictions. If that’s the case, you can choose to select the stack and read the message that will display on the *Events* tab or delete the resources manually by identifying the resources that were created as a result of the Quick Start template deployment as described in the Technical requirements section of this deployment guide.

== Best practices for using {partner-product-short-name} on AWS

Change the following before deploying this Quick Start on production workloads:

* This architecture uses a single instance and Availability Zone for the implementation of one Auto Scaling group to save costs. For a production deployment, we recommend you have your instances span across two or more Availability Zones for high availability after reviewing your environment and corresponding requirements.
* The class of CIDR for the VPC subnets is configured as a fixed class of 10.10.x.x or 10.100.x.x. You can change them as needed by modifying the template file before deployment.
* This Quick Start environment is configured for testing purposes, so some NACLs are set to open and do not have traffic control in place. Make sure you adopt stronger NACL policies to meet your security requirements before deploying the template.
* You can build your personal endpoints for AWS services.

== Security

Ensuring security and complying with relative laws are a shared responsibility between AWS and the customer. We recommend that customers become familiar with AWS Shared Responsibility Model before applying this solution to their production workloads.

This solution implements some of the summarized control mechanisms from the ISMS-P reference architecture, but not all recommendations to achieve each ISMS-P control are included in this Quick Start. For the guide specific to ISMS-P, see other documents or visit the https://aws.amazon.com/ko/compliance/k-isms/?nc1=h_ls[Korea Information Security Management System] page and follow the instructions.

We recommend to always seek the latest version for the source files and deployment guide for possible updates on the ISMS-P Quick Start features and guide.

The following is the controls that are not included in this solution or need additional description:

* This ISMS-P Quick Start provides internet gateways for internet connectivity, which simplifies the deployment to the level of a PoC. If you’re planning to store sensitive information in the solution, ensure that you review the ISMS-P package guidelines and comply with controls. Also, consider adopting data-in-transit encryption and AWS Direct Connect (DX) along with VPN or HTTP.
* To simplify the build, this architecture uses a DNS provided by Amazon VPC. You may consider using an EC2 based or your own in-house developed DNS service.
* The root volume of Amazon EC2 instances is not encrypted. See the New – Encrypted EBS Boot Volumes page before storing sensitive information.
* No remediation has been applied for non-compliant AWS resources by AWS Config rules in this Quick Start. Visit the https://docs.aws.amazon.com/ko_kr/config/latest/developerguide/remediation.html[Remediating Noncompliant AWS Resources by AWS Config Rules] page for more information.
* Consider adopting AWS KMS or a 3^rd^ party solution to minimize the exposure of critical data to the outside world. See the https://docs.aws.amazon.com/ko_kr/kms/?id=docs_gateway[AWS KMS] and https://docs.aws.amazon.com/ko_kr/aws-crypto-tools/?id=docs_gateway[Crypto Tools] pages for details.
* AWS WAF is designed to apply five rules as a priority so that they would be considered starting points rather than a comprehensive set of rules prepared for a production environment. We recommend you determine if these rules fit your environment and security policies and apply only the rules you feel necessary for your production environment. Also, the AWS WAF action is set to Count by default to prevent tasks from being blocked. For more information, see https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-action.html[AWS WAF rule action].


== Other useful information

* If you’re considering expanding the use of AWS Organizations and single sign-on (SSO) to operate a multi-account environment or to manage IAM users effectively, visit the https://docs.aws.amazon.com/ko_kr/organizations/latest/userguide/services-that-can-integrate-peregrine.html[AWS Single Sign-On and AWS Organizations] page.

* Review the logging and analysis features using AWS CloudTrail and AWS CloudWatch to track the creation, modification or deletion of AWS IAM user activities, infrastructure and AWS services. For more information, see the https://docs.aws.amazon.com/ko_kr/cloudtrail/index.html[AWS CloudTrail] and https://aws.amazon.com/ko/cloudwatch/features/[Amazon CloudWatch] pages.
* If you’re planning to run applications or services on this infrastructure created as a result of this Quick Start deployment, find ways to securely store and manage database credentials, API keys and other security information against exposure. For details, visit the https://aws.amazon.com/ko/secrets-manager/[AWS Secret Manager] and AWS Systems Manager https://docs.aws.amazon.com/ko_kr/systems-manager/latest/userguide/systems-manager-parameter-store.html[Parameter Store] pages.
* Consider using AWS Config and AWS Config rules to continuously monitor, evaluate, and remediate security vulnerabilities. For details, see the https://aws.amazon.com/ko/config/[AWS Config] page.
